name: Daily LeetCode Submission

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs on a schedule (e.g., every day at 6:30 UTC)
  schedule:
    - cron: '30 6 * * *'

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run submission script
        run: npm start
        env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          CSRF_TOKEN: ${{ secrets.CSRF_TOKEN }}